### ISSUE TITLE
Rejects ids with certain common characters

### ISSUE THREAD

**Issue by dobesv** [golgote/lua-resty-hawk#1]
This library validates that the hawk attributes use only a very narrow character set.  Unfortunately, this seems to be overly exclusive.

I'm wondering why - is it possible to remove this check?  What are you trying to prevent?

Perhaps it would be sufficient to just require all the characters are printable ASCII?

e.g. [ -~]

**Comment by dobesv** [comment]
See also https://github.com/golgote/lua-resty-hawk/pull/3

**Comment by dobesv** [comment]
See also https://github.com/golgote/lua-resty-hawk/pull/4

**Comment by golgote** [comment]
Fixed in https://github.com/golgote/lua-resty-hawk/pull/6
